### PR TITLE
passport-oauth2@1.3.x

### PR DESCRIPTION
**Pull request by siacomuzzi**
update to the latest version of `passport-oauth2` (there are no breaking changes)

### CODE REVIEW

**Comment by siacomuzzi** [comment]
Could you please review/merge this? It's the only reason why we have to use our own fork

Thanks!

**Comment by stevebest** [comment]
Sorry for not responding -- can't find much time for open-source nowadays. Thanks for contributing, BTW!

Are there any particular reasons why you need the updated passport-oauth2, other than greenkeeping?

Will bump later when I get to my home machine.

**Comment by siacomuzzi** [comment]
I want the [pluggable state store](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L99-L107) provided by latest version of `passport-oauth2`

**Comment by stevebest** [comment]
Published as 0.3.1

Thanks!

**Comment by siacomuzzi** [comment]
Thanks!

**Pull request merged**
