### PR TITLE
Enable https

### PR DESCRIPTION
**Pull request by qu1ze**

### CODE REVIEW

**Comment by stevebest** [comment]
Can you link me to VK docs on https? I can't seem to find the requirement for this parameter.

**Comment by qu1ze** [comment]
@stevebest https://vk.com/dev/api_requests

**Comment by stevebest** [comment]
Huh, indeed. VK API never ceases to amaze me with its stupidities!

Will merge and `npm publish` later today, I hope.

**Comment by qu1ze** [comment]
@stevebest great, thank you!

**Comment by stevebest** [comment]
Published as `0.4.0`. Thanks for your contribution!

**Pull request merged**
